import os
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch


def generate_pdf(report_data, output_path):
    # Create PDF document
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    story = []

    # =====================================================
    # PDF HEADER (NFSU LOGO + TITLE)
    # =====================================================
    logo_path = os.path.join("static", "logo 2.png")

    if os.path.exists(logo_path):
        logo = Image(logo_path, width=3.0 * inch, height=1.1 * inch)
        story.append(logo)

    story.append(Spacer(1, 10))

    story.append(Paragraph(
        "<b>APK Forensic Analysis Report</b><br/>"
        "Gujarat Police – Cyber Cell",
        styles["Title"]
    ))

    story.append(Spacer(1, 20))

    # =====================================================
    # APK IDENTIFICATION
    # =====================================================
    story.append(Paragraph("<b>APK Identification</b>", styles["Heading2"]))
    story.append(Paragraph(f"File Name: {report_data['apk_name']}", styles["Normal"]))
    story.append(Paragraph(f"SHA-256 Hash: {report_data['sha256']}", styles["Normal"]))
    story.append(Paragraph(f"File Size: {report_data['file_size']}", styles["Normal"]))
    story.append(Paragraph(f"Analysis Time: {report_data['analysis_time']}", styles["Normal"]))
    story.append(Spacer(1, 15))

    # =====================================================
    # PERMISSIONS
    # =====================================================
    story.append(Paragraph("<b>Requested Permissions</b>", styles["Heading2"]))
    for perm in report_data["all_permissions"]:
        story.append(Paragraph(f"- {perm}", styles["Normal"]))
    story.append(Spacer(1, 15))

    # =====================================================
    # DANGEROUS PERMISSIONS
    # =====================================================
    story.append(Paragraph("<b>Dangerous Permissions</b>", styles["Heading2"]))
    if report_data["dangerous_permissions"]:
        for d in report_data["dangerous_permissions"]:
            story.append(Paragraph(f"- {d}", styles["Normal"]))
    else:
        story.append(Paragraph("No dangerous permissions detected.", styles["Normal"]))
    story.append(Spacer(1, 15))

    # =====================================================
    # RISK ASSESSMENT
    # =====================================================
    story.append(Paragraph("<b>Risk Assessment</b>", styles["Heading2"]))
    story.append(Paragraph(f"Risk Score: {report_data['risk_score']}", styles["Normal"]))
    story.append(Paragraph(f"Final Verdict: {report_data['verdict']}", styles["Normal"]))

    for reason in report_data["reasons"]:
        story.append(Paragraph(f"- {reason}", styles["Normal"]))
    story.append(Spacer(1, 15))

    # =====================================================
    # NETWORK IOCs
    # =====================================================
    story.append(Paragraph("<b>Network Indicators of Compromise</b>", styles["Heading2"]))

    if report_data["urls"]:
        story.append(Paragraph("Detected URLs:", styles["Normal"]))
        for u in report_data["urls"]:
            story.append(Paragraph(f"- {u}", styles["Normal"]))
    else:
        story.append(Paragraph("No URLs detected.", styles["Normal"]))

    if report_data["ips"]:
        story.append(Paragraph("Detected IP Addresses:", styles["Normal"]))
        for ip in report_data["ips"]:
            story.append(Paragraph(f"- {ip}", styles["Normal"]))
    else:
        story.append(Paragraph("No IP addresses detected.", styles["Normal"]))

    story.append(Spacer(1, 15))

    # =====================================================
    # EVIDENCE INTEGRITY NOTE
    # =====================================================
    story.append(Paragraph("<b>Evidence Integrity Note</b>", styles["Heading2"]))
    story.append(Paragraph(
        "This report is generated using static analysis only. "
        "The APK was not executed. Hash-based verification ensures "
        "digital evidence integrity.",
        styles["Normal"]
    ))
    story.append(Spacer(1, 20))

    # =====================================================
    # REPORT CREDIT
    # =====================================================
    story.append(Paragraph(
        "<i>Report generated by Daksh Chauhan @ "
        "National Forensic Sciences University (NFSU), Gandhinagar</i>",
        styles["Normal"]
    ))

    # Build PDF
    doc.build(story)
